export const monthlyCard = [
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
];

export const yearlyCard = [
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
  {
    package: "free",
    price: "$0",
    ApiCalls: "Unlimited API calls",
    rate: "5rq/s",
    support: "Community Support",
    testnet: "API Testnet",
    data: "Market Data",
  },
];
